# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'How to Prof'
description:      'The missing manual for professors'
url:              http://mdwelsh.github.io
baseurl:          /

author:
  name:           'Matt Welsh'
  url:            http://www.mdw.la

paginate:         5
